version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.13

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run lint

  deploy:
    docker:
      - image: circleci/node:12.13
    steps:
      - checkout
      - run:
          name: deploy
          command: ssh -oStrictHostKeyChecking=no -v $DEVELOP_USER@$DEVELOP_IP "cd /home/$DEVELOP_USER; sh deploy-frontend.sh $CIRCLE_BRANCH;"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
